In [1]:
# shape , reshape , flatten , ravel

In [2]:
import numpy as np

In [4]:
a= np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a.ndim, a.shape


(2, (2, 4))

In [8]:
a.reshape(1,7)

ValueError: cannot reshape array of size 8 into shape (1,7)

In [11]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
#arrange, linespace, range, random, zero, one

In [14]:
np.arange(1,5)

array([1, 2, 3, 4])

In [16]:
np.arange(1,9 ,dtype = 'float')

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [17]:
np.linspace(1,9 ,dtype = 'float')

array([1.        , 1.16326531, 1.32653061, 1.48979592, 1.65306122,
       1.81632653, 1.97959184, 2.14285714, 2.30612245, 2.46938776,
       2.63265306, 2.79591837, 2.95918367, 3.12244898, 3.28571429,
       3.44897959, 3.6122449 , 3.7755102 , 3.93877551, 4.10204082,
       4.26530612, 4.42857143, 4.59183673, 4.75510204, 4.91836735,
       5.08163265, 5.24489796, 5.40816327, 5.57142857, 5.73469388,
       5.89795918, 6.06122449, 6.2244898 , 6.3877551 , 6.55102041,
       6.71428571, 6.87755102, 7.04081633, 7.20408163, 7.36734694,
       7.53061224, 7.69387755, 7.85714286, 8.02040816, 8.18367347,
       8.34693878, 8.51020408, 8.67346939, 8.83673469, 9.        ])

In [18]:
from numpy import random

In [19]:
random.randint(1,6)

5

In [20]:
range(1,10)

range(1, 10)

In [22]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#where

In [24]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
np.where(a>10)

(array([], dtype=int64), array([], dtype=int64))

In [28]:
index=np.where(a>10)
a[index]

array([], dtype=int64)