In [1]:
import numpy as np

In [2]:
# Patient IDs
patient_ids = np.arange(1,11)

# Patient Ages
ages = np.array([25,42,36,50,61,29,40,55,48,33])

# Heart Rate
heart_rate = np.array([72,88,76,90,85,70,79,95,82,74])

# Temperature
temperature = np.array([98.6,99.2,98.4,100.1,99.5,98.2,98.8,101.0,99.0,98.5])

print(patient_ids)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
print("Patient IDs")
print(patient_ids)

print("\nPatient Ages")
print(ages)

print("\nHeart Rate")
print(heart_rate)

print("\nTemperature")
print(temperature)

Patient IDs
[ 1  2  3  4  5  6  7  8  9 10]

Patient Ages
[25 42 36 50 61 29 40 55 48 33]

Heart Rate
[72 88 76 90 85 70 79 95 82 74]

Temperature
[ 98.6  99.2  98.4 100.1  99.5  98.2  98.8 101.   99.   98.5]


In [4]:
print("Shape of Age Array :",ages.shape)
print("Shape of Heart Rate :",heart_rate.shape)

Shape of Age Array : (10,)
Shape of Heart Rate : (10,)


In [5]:
print("Average Age :",np.mean(ages))
print("Minimum Age :",np.min(ages))
print("Maximum Age :",np.max(ages))

print("Average Heart Rate :",np.mean(heart_rate))

print("Highest Temperature :",np.max(temperature))
print("Lowest Temperature :",np.min(temperature))

Average Age : 41.9
Minimum Age : 25
Maximum Age : 61
Average Heart Rate : 81.1
Highest Temperature : 101.0
Lowest Temperature : 98.2


In [6]:
print("Total Age :",np.sum(ages))
print("Total Heart Rate :",np.sum(heart_rate))

Total Age : 419
Total Heart Rate : 811


In [7]:
print("First Patient Age :",ages[0])

print("Last Patient Age :",ages[-1])

print("Third Patient Temperature :",temperature[2])

First Patient Age : 25
Last Patient Age : 33
Third Patient Temperature : 98.4


In [8]:
print("First Five Ages")

print(ages[:5])

print("Last Three Heart Rates")

print(heart_rate[-3:])

First Five Ages
[25 42 36 50 61]
Last Three Heart Rates
[95 82 74]


In [9]:
fever = np.where(temperature>99)

print(fever)

print("Patients having fever")

print(patient_ids[fever])

(array([1, 3, 4, 7]),)
Patients having fever
[2 4 5 8]


In [10]:
old_patients=np.where(ages>40)

print(patient_ids[old_patients])

[2 4 5 8 9]


In [11]:
high=np.where(heart_rate>85)

print(patient_ids[high])

[2 4 8]


In [12]:
patient_matrix=ages.reshape(2,5)

print(patient_matrix)

[[25 42 36 50 61]
 [29 40 55 48 33]]


In [13]:
print(patient_matrix.flatten())

[25 42 36 50 61 29 40 55 48 33]


In [14]:
print(patient_matrix.ravel())

[25 42 36 50 61 29 40 55 48 33]


In [15]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
print(np.linspace(1,100,10))

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [18]:
random_bp=np.random.randint(90,150,10)

print(random_bp)

[143  98 149 117 108 120 147  95  93 113]


In [19]:
print("Hospital Report ")

print("Total Patients :",len(patient_ids))

print("Average Age :",np.mean(ages))

print("Average Heart Rate :",np.mean(heart_rate))

print("Highest Temperature :",np.max(temperature))

print("Patients with Fever :",patient_ids[np.where(temperature>99)])

print("Patients Above 40 :",patient_ids[np.where(ages>40)])


Hospital Report 
Total Patients : 10
Average Age : 41.9
Average Heart Rate : 81.1
Highest Temperature : 101.0
Patients with Fever : [2 4 5 8]
Patients Above 40 : [2 4 5 8 9]
